### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by SubstituteR**
I will change more as I look through the code.

### CODE REVIEW

**Comment by miltoncandelero** [comment]
> //Please consider allowing the user to decide this.  Most TCP/UDP calls will automatically bring the firewall allowance window up.  Doing so should also remove the administrative requirement.

The httpserver uses HttpListener. HttpListener not only does not trigger a firewall warning but even if it did, is not the exe who is using the network. HttpListener uses http.sys kernel module and this is what should be allowed through the firewall (thats why I poke a global hole.)

> Consider using REGEX for this.  It is less code, and could be faster.  See: https://goo.gl/580E5x

Is regex really faster? last time I used it (looong time ago), it was cool for flexibility but incredibly slow compared to raw string comparing.

**Comment by SubstituteCS** [comment]
The REGEX is more extensible (if you extend the program more.)  
An httpserver is just a TCP listener on (default) port 80.  I can look into writing a homebrew httpserver.

**Comment by miltoncandelero** [comment]
If you could write a socket based or tcplistener (Anything **but** httplistener) server, that would be awesome. ❤️

**Comment by SubstituteCS** [comment]
I can try :Kappa:, I don't use C# often, but it's not too different.

**Pull request merged**
